# Generated by Django 4.2.30 on 2026-05-22 07:38

import audios.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=audios.models.audio_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])], verbose_name='音频文件')),
                ('filename', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_path', models.CharField(max_length=500, verbose_name='文件路径')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='文件大小(字节)')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='时长(秒)')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='auth.group', verbose_name='所属分组')),
            ],
            options={
                'verbose_name': '音频',
                'verbose_name_plural': '音频管理',
                'ordering': ('-upload_time', '-id'),
            },
        ),
        migrations.CreateModel(
            name='UserListened',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listened_time', models.DateTimeField(auto_now_add=True, verbose_name='听完时间')),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listened_users', to='audios.audio', verbose_name='音频')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listened_audios', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '已听记录',
                'verbose_name_plural': '已听记录',
                'ordering': ('-listened_time', '-id'),
                'indexes': [models.Index(fields=['user', '-listened_time'], name='user_listened_time_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='userlistened',
            constraint=models.UniqueConstraint(fields=('user', 'audio'), name='user_audio_listened_unique'),
        ),
        migrations.AddIndex(
            model_name='audio',
            index=models.Index(fields=['group', '-upload_time'], name='audio_group_time_idx'),
        ),
        migrations.AddIndex(
            model_name='audio',
            index=models.Index(fields=['-upload_time'], name='audio_upload_time_idx'),
        ),
    ]
