# Generated by Django 4.2.30 on 2026-05-23 15:50

import audios.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to=audios.models.audio_cover_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), audios.models.validate_audio_cover_size], verbose_name='音频图片'),
        ),
    ]
