# Generated by Django 4.2.30 on 2026-05-25 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0002_audio_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioCleanup',
            fields=[
            ],
            options={
                'verbose_name': '音频清理',
                'verbose_name_plural': '音频清理',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('audios.audio',),
        ),
    ]
