# Generated by Django 4.2.30 on 2026-06-10 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('audios', '0003_audiocleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioUploadToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Token 名称')),
                ('token_hash', models.CharField(blank=True, editable=False, max_length=64, unique=True, verbose_name='Token 哈希')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最后使用时间')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_upload_tokens', to='auth.group', verbose_name='绑定分组')),
            ],
            options={
                'verbose_name': '上传 Token',
                'verbose_name_plural': '上传 Token',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['token_hash'], name='upload_token_hash_idx'), models.Index(fields=['group', 'is_active'], name='upload_token_group_idx')],
            },
        ),
    ]
