# Generated by Django 4.2.30 on 2026-05-21 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managedgroup',
            options={'verbose_name': '分组', 'verbose_name_plural': '分组管理'},
        ),
        migrations.AlterModelOptions(
            name='manageduser',
            options={'verbose_name': '账号', 'verbose_name_plural': '账号管理'},
        ),
        migrations.AlterModelOptions(
            name='usergroupmembership',
            options={'ordering': ('user_id',), 'verbose_name': '用户分组关系', 'verbose_name_plural': '用户分组关系'},
        ),
    ]
