# Generated by Django 4.2.30 on 2026-05-23 15:26

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_groupprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofile',
            name='default_cover',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.group_default_cover_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), accounts.models.validate_group_cover_size], verbose_name='Audio Default Image'),
        ),
    ]
