# Generated by Django 4.2.30 on 2026-05-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_groupprofile_default_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofile',
            name='is_default_group',
            field=models.BooleanField(default=False, verbose_name='Default Group'),
        ),
    ]
