# Generated by Django 4.2.30 on 2026-05-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_groupprofile_is_default_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofile',
            name='weight',
            field=models.PositiveIntegerField(default=100, verbose_name='Weight'),
        ),
    ]
